version: '3.7'
services:
  server:
    build: .
    ports:
      - 8080:8080
    volumes:
      - $HOME/.m2:/root/.m2
    depends_on:
      - db
  db:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

